vich_uploader:
    db_driver: orm

    mappings:
       category:
           uri_prefix: /images/category
           upload_destination: '%kernel.project_dir%/public/images/category'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        blog:
           uri_prefix: /images/blog
           upload_destination: '%kernel.project_dir%/public/images/blog'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        service:
           uri_prefix: /images/service
           upload_destination: '%kernel.project_dir%/public/images/service'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        team:
           uri_prefix: /images/team
           upload_destination: '%kernel.project_dir%/public/images/team'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer